/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package watch;
import java.awt.Font;
import java.awt.Image;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class SurveyFrame extends javax.swing.JFrame {

    /**
     * Creates new form SurveyFrame
     */
    public SurveyFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Survey Form");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setForeground(new java.awt.Color(240, 240, 240));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel10.setText("Alarm");

        jButton3.setBackground(new java.awt.Color(255, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jRadioButton1.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jRadioButton1.setText("12-hour ");
        jRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jRadioButton2.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jRadioButton2.setText("24-hour");

        jRadioButton3.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jRadioButton3.setText("Both");

        jCheckBox1.setBackground(new java.awt.Color(153, 204, 255));

        jCheckBox2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel11.setText("Health Measurement");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel12.setText("Count Steps & Distance");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel13.setText("Reply Message");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel14.setText("Receive Call");

        jCheckBox3.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Buxton Sketch", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Survey For Watch Details That You Prefer");

        jCheckBox4.setBackground(new java.awt.Color(153, 204, 255));
        jCheckBox4.setToolTipText("");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jCheckBox5.setBackground(new java.awt.Color(153, 204, 255));

        jCheckBox6.setBackground(new java.awt.Color(153, 204, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setText("Display Time         :");

        jCheckBox7.setBackground(new java.awt.Color(153, 204, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel3.setText("Read Time Format :");

        jCheckBox8.setBackground(new java.awt.Color(153, 204, 255));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel4.setText("Display Date          :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel5.setText("Display Day           :");

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("OTHER FEATURES OF WATCH THAT YOU NEED : ");

        jComboBox4.setBackground(new java.awt.Color(51, 153, 255));
        jComboBox4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "          <CHOOSE TYPE OF DISPLAY>", " Analog Form ( through hands on a dial )", " Digits Form", " Analog Form / Digits Form" }));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel7.setText("Waterproof");

        jComboBox5.setBackground(new java.awt.Color(51, 153, 255));
        jComboBox5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "           < CHOOSE TYPE OF DISPLAY >", " dd (Exp : 23)", " dd/MM/yyyy  (Exp : 23/05/2020)", " dd MMM yyyy (Exp : 23 May 2020)" }));
        jComboBox5.setMinimumSize(new java.awt.Dimension(239, 21));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel8.setText("Stopwatch");

        jComboBox6.setBackground(new java.awt.Color(51, 153, 255));
        jComboBox6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "           < CHOOSE TYPE OF DISPLAY >", " Short-form (Exp: Sat)", " Full-form (Exp: SATURDAY)" }));
        jComboBox6.setMinimumSize(new java.awt.Dimension(239, 21));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel9.setText("Light");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 204));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Click Here To Know Other Type Of Watch");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(51, 51, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.png"))); // NOI18N
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Show Picture Of Watch :");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jCheckBox3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBox2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(445, 835, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jCheckBox2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jCheckBox3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jCheckBox4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jCheckBox5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jCheckBox6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jCheckBox7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jCheckBox8))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==jButton3){
            
            int a=JOptionPane.showConfirmDialog(null,"DO YOU REALLY WANT TO EXIT ?");
            if(a==JOptionPane.YES_OPTION){
                this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                System.exit(0);
            }
            else{
   
            } 
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (evt.getSource()== jButton1){
            if (jComboBox4.getSelectedItem().equals(" Analog Form ( through hands on a dial )")||jComboBox4.getSelectedItem().equals(" Analog Form / Digits Form")){
                if(jRadioButton1.isSelected()||jRadioButton2.isSelected()|| jRadioButton3.isSelected()){
                    if(jComboBox5.getSelectedItem().equals(" dd (Exp : 23)")||jComboBox5.getSelectedItem().equals(" dd/MM/yyyy  (Exp : 23/05/2020)")||jComboBox5.getSelectedItem().equals(" dd MMM yyyy (Exp : 23 May 2020)")){
                        if(jComboBox6.getSelectedItem().equals(" Short-form (Exp: Sat)")||jComboBox6.getSelectedItem().equals(" Full-form (Exp: SATURDAY)")){
                            if(jCheckBox1.isSelected()){
                                javax.swing.ImageIcon imageIcon=new javax.swing.ImageIcon(getClass().getResource("/Analog1.jpg"));
                                Image image = imageIcon.getImage();
                                Image newimg = image.getScaledInstance(320, 356, java.awt.Image.SCALE_SMOOTH);
                                imageIcon=new javax.swing.ImageIcon(newimg);
                                jLabel16.setIcon(imageIcon);
                                String text ="  According to the Survey, the type \n" +
                                "of watch that you need is Analog Watch. \n"+
                                "\n"   ;
                                String data= "*************************************\n" +
                                            "     Features of Analog Watch \n" +
                                            "*************************************\n" +
                                            "<<<<< BASIC FEATURES >>>>>\n" +
                                            "\n" +
                                            "Time (hh:mm)       : 3:45 PM\n" +
                                            "Date (dd)          : 23\n" +
                                            "Day                : Sat\n" +
                                            "Display Time       : Through hands on a dial\n"+
                                            "Read Time Format   : 12-hour format\n" +
                                            "Waterproof Level   : Weak\n" +
                                            "Battery's Life     : Long-lasting\n" +
                                            "\n" +
                                            "<<<< SPECIAL FEATURES >>>>\n" +
                                            "\n" +
                                            "Motion             : \"Ticking\" \n" +
                                            "Move With 3 Hands  : Hours hand\n" +
                                            "                     Minutes hand\n" +
                                            "                     Seconds hand";
                                Font font = new Font("Monospaced", Font.BOLD, 14);
                                jTextArea1.setFont(font);                                
                                jTextArea1.setText(text+data);
                            }
                        }
                    }
                }
            }
            if (jComboBox4.getSelectedItem().equals(" Digits Form")||jComboBox4.getSelectedItem().equals(" Analog Form / Digits Form")){
                if(jRadioButton1.isSelected()||jRadioButton2.isSelected()|| jRadioButton3.isSelected()){
                    if(jComboBox5.getSelectedItem().equals(" dd (Exp : 23)")||jComboBox5.getSelectedItem().equals(" dd/MM/yyyy  (Exp : 23/05/2020)")||jComboBox5.getSelectedItem().equals(" dd MMM yyyy (Exp : 23 May 2020)")){
                        if(jComboBox6.getSelectedItem().equals(" Short-form (Exp: Sat)")||jComboBox6.getSelectedItem().equals(" Full-form (Exp: SATURDAY)")){
                            if(jCheckBox1.isSelected()||jCheckBox2.isSelected()||jCheckBox3.isSelected()||jCheckBox4.isSelected()){
                                javax.swing.ImageIcon imageIcon=new javax.swing.ImageIcon(getClass().getResource("/Digital.jpg"));
                                Image image = imageIcon.getImage();
                                Image newimg = image.getScaledInstance(320, 356, java.awt.Image.SCALE_SMOOTH);
                                imageIcon=new javax.swing.ImageIcon(newimg);
                                jLabel16.setIcon(imageIcon);
                                String text1 ="   According to the Survey, the type\n" +
                                "of watch that you need is Digital Watch. \n"+"\n";
                                String data1 = "************************************\n" +
                                            "     Features of Digital Watch \n" +
                                            "************************************\n" +
                                            "<<<<< BASIC FEATURES >>>>>\n" +
                                            "\n" +
                                            "Time 12-hour Format (hh:mm:ss) : 3:45:46 PM\n" +
                                            "Time 24-hour Format (hh:mm:ss) : 15:45:46\n" +
                                            "Date (dd/MM/yyyy) : 23/05/2020\n" +
                                            "Day               : Sat\n" +
                                            "Display Time      : Digits and Numbers Form (usually on LED screen)\n" +
                                            "Read Time Format  : 12-hour or 24-hour format\n" +
                                            "Waterproof Level  : Strong\n" +
                                            "Battery's Life    : Not lasting\n" +
                                            "\n" +
                                            "<<<< SPECIAL FEATURES >>>>\n" +
                                            "\n" +
                                            "Stopwatch         : Counting Timer\n" +
                                            "Alarm             : Vibration\n" +
                                            "Light             : ON or OFF";
                                Font font = new Font("Monospaced", Font.BOLD, 14);
                                jTextArea1.setFont(font);
                                jTextArea1.setText(text1+data1);
                            }

                        }
                    }
                }
            }
            if(jComboBox4.getSelectedItem().equals(" Analog Form / Digits Form")||jComboBox4.getSelectedItem().equals(" Digits Form")||jComboBox4.getSelectedItem().equals(" Analog Form ( through hands on a dial )")){
                if(jRadioButton1.isSelected()||jRadioButton2.isSelected()|| jRadioButton3.isSelected()){
                    if(jComboBox5.getSelectedItem().equals(" dd (Exp : 23)")||jComboBox5.getSelectedItem().equals(" dd/MM/yyyy  (Exp : 23/05/2020)")||jComboBox5.getSelectedItem().equals(" dd MMM yyyy (Exp : 23 May 2020)")){
                        if(jComboBox6.getSelectedItem().equals(" Short-form (Exp: Sat)")||jComboBox6.getSelectedItem().equals(" Full-form (Exp: SATURDAY)")){
                            if(jCheckBox5.isSelected()||jCheckBox6.isSelected()||jCheckBox7.isSelected()||jCheckBox8.isSelected()){
                                javax.swing.ImageIcon imageIcon=new javax.swing.ImageIcon(getClass().getResource("/Smart.jpg"));
                                Image image = imageIcon.getImage();
                                Image newimg = image.getScaledInstance(255, 356, java.awt.Image.SCALE_SMOOTH);
                                imageIcon=new javax.swing.ImageIcon(newimg);
                                jLabel16.setIcon(imageIcon);
                                String text2 ="      According to the Survey, the type\n" +
                                "    of watch that you need is Smart Watch. \n"+"\n";
                                String data2 ="***********************************\n" +
                                            "     Features of Smart Watch \n" +
                                            "***********************************\n" +
                                            "<<<<< BASIC FEATURES >>>>>\n" +
                                            "\n" +
                                            "Time 12-hour Format (hh:mm:ss)  : 3:45:46 PM\n" +
                                            "Time 24-hour Format (hh:mm:ss)  : 15:45:46 Malaysia Time\n" +
                                            "Date (dd/MM/yyyy)&(dd MMM yyyy) : 23/05/2020 & 23 May 2020\n" +
                                            "Day                : SATURDAY or Sat\n" +
                                            "Display Time       : Digits form or Analog form\n" +
                                            "Read Time Format   : 12-hour or 24-hour format\n" +
                                            "Waterproof Level   : Strong\n" +
                                            "Battery's Life     : Not lasting\n" +
                                            "Stopwatch          : Counting Timer\n" +
                                            "Alarm              : Vibration\n" +
                                            "Light              : ON or OFF\n" +
                                            "\n" +
                                            "<<<< SPECIAL FEATURES >>>>\n" +
                                            "\n" +
                                            "Count              : Steps, Distance\n" +
                                            "Measure            : Heart Rate, Calories, Blood Pressure\n" +
                                            "Others Features    : TouchScreen!!!\n" +
                                            "                     Allows Connection to Phone.\n" +
                                            "                     Reply to Messages.\n" +
                                            "                     Receive Calls Instantly.";
                                Font font = new Font("Monospaced", Font.BOLD, 12);
                                jTextArea1.setFont(font);
                                jTextArea1.setText(text2+data2);
                            }
                        }
                    }
                }
            }
            if(jComboBox4.getSelectedItem().equals(" Analog Form ( through hands on a dial )")){
                if(jRadioButton1.isSelected()||jRadioButton2.isSelected()|| jRadioButton3.isSelected()){
                    if(jComboBox5.getSelectedItem().equals(" dd (Exp : 23)")||jComboBox5.getSelectedItem().equals(" dd/MM/yyyy  (Exp : 23/05/2020)")||jComboBox5.getSelectedItem().equals(" dd MMM yyyy (Exp : 23 May 2020)")){
                        if(jComboBox6.getSelectedItem().equals(" Short-form (Exp: Sat)")||jComboBox6.getSelectedItem().equals(" Full-form (Exp: SATURDAY)")){
                            if(jCheckBox2.isSelected()||jCheckBox3.isSelected()||jCheckBox4.isSelected()){
                                javax.swing.ImageIcon imageIcon=new javax.swing.ImageIcon(getClass().getResource("/Smart.jpg"));
                                Image image = imageIcon.getImage();
                                Image newimg = image.getScaledInstance(255, 356, java.awt.Image.SCALE_SMOOTH);
                                imageIcon=new javax.swing.ImageIcon(newimg);
                                jLabel16.setIcon(imageIcon);
                                String text3 ="      According to the Survey, the type \n" +
                                "    of watch that you need is Smart Watch. \n"+"\n";
                               String data3 ="***********************************\n" +
                                            "     Features of Smart Watch \n" +
                                            "***********************************\n" +
                                            "<<<<< BASIC FEATURES >>>>>\n" +
                                            "\n" +
                                            "Time 12-hour Format (hh:mm:ss)  : 3:45:46 PM\n" +
                                            "Time 24-hour Format (hh:mm:ss)  : 15:45:46 Malaysia Time\n" +
                                            "Date (dd/MM/yyyy)&(dd MMM yyyy) : 23/05/2020 & 23 May 2020\n" +
                                            "Day                : SATURDAY or Sat\n" +
                                            "Display Time       : Digits form or Analog form\n" +
                                            "Read Time Format   : 12-hour or 24-hour format\n" +
                                            "Waterproof Level   : Strong\n" +
                                            "Battery's Life     : Not lasting\n" +
                                            "Stopwatch          : Counting Timer\n" +
                                            "Alarm              : Vibration\n" +
                                            "Light              : ON or OFF\n" +
                                            "\n" +
                                            "<<<< SPECIAL FEATURES >>>>\n" +
                                            "\n" +
                                            "Count              : Steps, Distance\n" +
                                            "Measure            : Heart Rate, Calories, Blood Pressure\n" +
                                            "Others Features    : TouchScreen!!!\n" +
                                            "                     Allows Connection to Phone.\n" +
                                            "                     Reply to Messages.\n" +
                                            "                     Receive Calls Instantly.";
                                Font font = new Font("Monospaced", Font.BOLD, 12);
                                jTextArea1.setFont(font);
                                jTextArea1.setText(text3+data3);
                            }

                        }
                    }
                }
            }

            if(jComboBox4.getSelectedItem().equals("          <CHOOSE TYPE OF DISPLAY>"))
            {
                JOptionPane.showMessageDialog(null,"Please Select (Display Time)");
            }
            if(!jRadioButton1.isSelected()&&!jRadioButton2.isSelected()&&!jRadioButton3.isSelected()){

                JOptionPane.showMessageDialog(null,"Please Select (Read Time Format)");
            }
            if(jComboBox5.getSelectedItem().equals("           < CHOOSE TYPE OF DISPLAY >"))
            {
                JOptionPane.showMessageDialog(null,"Please Select (Display Date)");
            }
            if(jComboBox6.getSelectedItem().equals("           < CHOOSE TYPE OF DISPLAY >"))
            {
                JOptionPane.showMessageDialog(null,"Please Select (Display Day)");
            }

            if(!jCheckBox1.isSelected()&&!jCheckBox2.isSelected()&&!jCheckBox3.isSelected()&&!jCheckBox4.isSelected()&&!jCheckBox5.isSelected()&&!jCheckBox6.isSelected()&&!jCheckBox7.isSelected()&&!jCheckBox8.isSelected()){

                JOptionPane.showMessageDialog(null,"Please Select (Other Features)");
            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (evt.getSource()== jButton2){
            jComboBox4.setSelectedIndex(0);
            jComboBox5.setSelectedIndex(0);
            jComboBox6.setSelectedIndex(0);
            jCheckBox1.setSelected(false);
            jCheckBox2.setSelected(false);
            jCheckBox3.setSelected(false);
            jCheckBox4.setSelected(false);
            jCheckBox5.setSelected(false);
            jCheckBox6.setSelected(false);
            jCheckBox7.setSelected(false);
            jCheckBox8.setSelected(false);
            jTextArea1.setText("");
            jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.png")));

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        if(evt.getSource()==jLabel15){
            this.dispose();
            WatchFrame w=new WatchFrame();
            w.setVisible(true);
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SurveyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SurveyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SurveyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SurveyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SurveyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
